version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install dependencies
          command: |
            rustup update stable
            rustup default stable
            rustup component add rustfmt-preview
            rustc --version --verbose
            cargo --version --verbose
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test --lib
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
